spring:
  datasource:
    url: jdbc:mysql://asyncsite-mysql:3306/iap_gateway_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true

  data:
    redis:
      host: asyncsite-redis

  kafka:
    bootstrap-servers: asyncsite-kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://asyncsite-eureka:8761/eureka/

feign:
  client:
    config:
      payment-core:
        url: http://asyncsite-payment-core:6082

# Payment Core Service URL
payment-core:
  url: http://asyncsite-payment-core:6082
